baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Baika'
theme = "websitetheme"

[params]
sitename = "Baika"
copyrights = "Baika"
defaultList = "global"
paginationLen = 3
projectsURL = "https://example.com"
brief_about = "<center>Welcome to Baika</center>"
[[menu.main]]
name = "Post"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Subscribe"
url = "/index.xml"
weight = 3

[[menu.main]]
name = "Uses"
url = "/uses"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Subscribe"
url = "/index.xml"
weight = 6